<a href="https://colab.research.google.com/github/manikantar585-lgtm/ML-23AG1A66F9/blob/main/Data_processing_ipynd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**importing dataset**

In [12]:
import pandas as pd
data=pd.read_csv('Name_Age_Gender_Marks_City - Sheet1 (1).csv')
data.head()

      Name   Age Gender  Marks      City
0     Mani  21.0      M   85.0       HYD
1     Ajay   NaN      M   92.0   Lon Don
2    megii  18.0      F   72.0       NaN
3    David  17.0      F    NaN   Lon don
4  Hemanth  23.0    NaN   64.0  New york

In [13]:
data.fillna({
    'Age':data['Age'].mean(),
    'Marks':data['Marks'].mean(),
    'City':'Unknown'
},inplace=True)
print(data)

      Name    Age Gender  Marks      City
0     Mani  21.00      M  85.00       HYD
1     Ajay  19.75      M  92.00   Lon Don
2    megii  18.00      F  72.00   Unknown
3    David  17.00      F  78.25   Lon don
4  Hemanth  23.00    NaN  64.00  New york

In [15]:
import pandas as pd
# create example data including duplicates
data ={
    'Name': ['Mani', 'ajay', 'Mani'],
    'Age': [18, 18, 18],
    'Gender': ['M','M','M'],
    'Marks': [85,92,85]
}
df=pd.DataFrame(data)
print("original data:")
print(df)
#Remove duplicates across all colums
df_no_duplicates=df.drop_duplicates()
print("\nAfter removing duplicates:")
print(df_no_duplicates)

original data:
   Name  Age Gender  Marks
0  Mani   18      M     85
1  ajay   18      M     92
2  Mani   18      M     85

After removing duplicates:
   Name  Age Gender  Marks
0  Mani   18      M     85
1  ajay   18      M     92